version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    
  blog.webapi:
    image: ${DOCKER_REGISTRY-}blogwebapi

  blogsimple.blazorapp:
    image: ${DOCKER_REGISTRY-}blogsimpleblazorapp