version: '3.4'

services:
  sqldata:
    container_name: mssql
    hostname: mssql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
  blog.webapi:
    container_name: blog.webapi
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - "ConnectionStrings:BlogDbContext=Server=mssql;Database=BlogDb;User Id=sa;Password=Pass@word;TrustServerCertificate=True"
    build:
      context: .
      dockerfile: Blog.WebApi/Dockerfile
    depends_on:
      - sqldata
    ports:
      - "5102:80"

  blogsimple.blazorapp:
    container_name: blogsimple.blazorapp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: BlogSimple.BlazorApp/Dockerfile
    depends_on:
      - blog.webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5103:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
